# Form implementation generated from reading ui file 'Widgets/PointerScanFilter/Form/PointerScanFilterDialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 190)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(400, 190))
        Dialog.setMaximumSize(QtCore.QSize(400, 190))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_Main = QtWidgets.QVBoxLayout()
        self.verticalLayout_Main.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_Main.setObjectName("verticalLayout_Main")
        self.horizontalLayout_PrevFile = QtWidgets.QHBoxLayout()
        self.horizontalLayout_PrevFile.setObjectName("horizontalLayout_PrevFile")
        self.label_PrevFile = QtWidgets.QLabel(parent=Dialog)
        self.label_PrevFile.setScaledContents(False)
        self.label_PrevFile.setObjectName("label_PrevFile")
        self.horizontalLayout_PrevFile.addWidget(self.label_PrevFile)
        self.lineEdit_PrevFile = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_PrevFile.setReadOnly(True)
        self.lineEdit_PrevFile.setObjectName("lineEdit_PrevFile")
        self.horizontalLayout_PrevFile.addWidget(self.lineEdit_PrevFile)
        self.pushButton_PrevFile = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_PrevFile.setObjectName("pushButton_PrevFile")
        self.horizontalLayout_PrevFile.addWidget(self.pushButton_PrevFile)
        self.verticalLayout_Main.addLayout(self.horizontalLayout_PrevFile)
        self.horizontalLayout_CurrentFile = QtWidgets.QHBoxLayout()
        self.horizontalLayout_CurrentFile.setObjectName("horizontalLayout_CurrentFile")
        self.label_CurrentFile = QtWidgets.QLabel(parent=Dialog)
        self.label_CurrentFile.setObjectName("label_CurrentFile")
        self.horizontalLayout_CurrentFile.addWidget(self.label_CurrentFile)
        self.lineEdit_CurrentFile = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_CurrentFile.setReadOnly(True)
        self.lineEdit_CurrentFile.setObjectName("lineEdit_CurrentFile")
        self.horizontalLayout_CurrentFile.addWidget(self.lineEdit_CurrentFile)
        self.pushButton_CurrentFile = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_CurrentFile.setObjectName("pushButton_CurrentFile")
        self.horizontalLayout_CurrentFile.addWidget(self.pushButton_CurrentFile)
        self.verticalLayout_Main.addLayout(self.horizontalLayout_CurrentFile)
        self.horizontalLayout_NewFile = QtWidgets.QHBoxLayout()
        self.horizontalLayout_NewFile.setObjectName("horizontalLayout_NewFile")
        self.label_NewFile = QtWidgets.QLabel(parent=Dialog)
        self.label_NewFile.setObjectName("label_NewFile")
        self.horizontalLayout_NewFile.addWidget(self.label_NewFile)
        self.lineEdit_NewFile = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_NewFile.setReadOnly(True)
        self.lineEdit_NewFile.setObjectName("lineEdit_NewFile")
        self.horizontalLayout_NewFile.addWidget(self.lineEdit_NewFile)
        self.pushButton_NewFile = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_NewFile.setObjectName("pushButton_NewFile")
        self.horizontalLayout_NewFile.addWidget(self.pushButton_NewFile)
        self.verticalLayout_Main.addLayout(self.horizontalLayout_NewFile)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_Main.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.verticalLayout_Main, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Compare & Filter Pointers"))
        self.label_PrevFile.setText(_translate("Dialog", "Previous Map:"))
        self.pushButton_PrevFile.setText(_translate("Dialog", "Browse"))
        self.label_CurrentFile.setText(_translate("Dialog", "Current Map:"))
        self.pushButton_CurrentFile.setText(_translate("Dialog", "Browse"))
        self.label_NewFile.setText(_translate("Dialog", "New Output Map:"))
        self.pushButton_NewFile.setText(_translate("Dialog", "Browse"))
