# Form implementation generated from reading ui file 'Widgets/PointerScanFilter/Form/PointerScanFilterDialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 129)
        Dialog.setMinimumSize(QtCore.QSize(400, 129))
        Dialog.setMaximumSize(QtCore.QSize(400, 129))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_File1Path = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_File1Path.setReadOnly(True)
        self.lineEdit_File1Path.setObjectName("lineEdit_File1Path")
        self.horizontalLayout.addWidget(self.lineEdit_File1Path)
        self.pushButton_File1Browse = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_File1Browse.setObjectName("pushButton_File1Browse")
        self.horizontalLayout.addWidget(self.pushButton_File1Browse)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_File2Path = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_File2Path.setReadOnly(True)
        self.lineEdit_File2Path.setObjectName("lineEdit_File2Path")
        self.horizontalLayout_2.addWidget(self.lineEdit_File2Path)
        self.pushButton_File2Browse = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_File2Browse.setObjectName("pushButton_File2Browse")
        self.horizontalLayout_2.addWidget(self.pushButton_File2Browse)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Filter Pointers"))
        self.label.setText(_translate("Dialog", "File 1:"))
        self.pushButton_File1Browse.setText(_translate("Dialog", "Browse"))
        self.label_2.setText(_translate("Dialog", "File 2:"))
        self.pushButton_File2Browse.setText(_translate("Dialog", "Browse"))
