# Form implementation generated from reading ui file 'EditTypeDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(235, 163)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox_ValueType = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_ValueType.setObjectName("comboBox_ValueType")
        self.verticalLayout.addWidget(self.comboBox_ValueType)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.comboBox_Endianness = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_Endianness.setObjectName("comboBox_Endianness")
        self.verticalLayout_3.addWidget(self.comboBox_Endianness)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_Hex = QtWidgets.QCheckBox(parent=Dialog)
        self.checkBox_Hex.setObjectName("checkBox_Hex")
        self.horizontalLayout_2.addWidget(self.checkBox_Hex)
        self.checkBox_Signed = QtWidgets.QCheckBox(parent=Dialog)
        self.checkBox_Signed.setObjectName("checkBox_Signed")
        self.horizontalLayout_2.addWidget(self.checkBox_Signed)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.widget_Length = QtWidgets.QWidget(parent=Dialog)
        self.widget_Length.setObjectName("widget_Length")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_Length)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_Length = QtWidgets.QLabel(parent=self.widget_Length)
        self.label_Length.setObjectName("label_Length")
        self.horizontalLayout_4.addWidget(self.label_Length)
        self.lineEdit_Length = QtWidgets.QLineEdit(parent=self.widget_Length)
        self.lineEdit_Length.setText("10")
        self.lineEdit_Length.setObjectName("lineEdit_Length")
        self.horizontalLayout_4.addWidget(self.lineEdit_Length)
        self.checkBox_ZeroTerminate = QtWidgets.QCheckBox(parent=self.widget_Length)
        self.checkBox_ZeroTerminate.setChecked(True)
        self.checkBox_ZeroTerminate.setObjectName("checkBox_ZeroTerminate")
        self.horizontalLayout_4.addWidget(self.checkBox_ZeroTerminate)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout.addWidget(self.widget_Length, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Type"))
        self.label.setText(_translate("Dialog", "Type"))
        self.label_2.setText(_translate("Dialog", "Endianness"))
        self.checkBox_Hex.setText(_translate("Dialog", "Hex"))
        self.checkBox_Signed.setText(_translate("Dialog", "Signed"))
        self.label_Length.setText(_translate("Dialog", "Length"))
        self.checkBox_ZeroTerminate.setText(_translate("Dialog", "Zero-Terminated"))
