# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LibPINCEReferenceWidget.ui'
#
# Created: Thu Feb  2 23:39:23 2017
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(887, 569)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget_TypeDefs = QtWidgets.QWidget(self.splitter)
        self.widget_TypeDefs.setObjectName("widget_TypeDefs")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_TypeDefs)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser_TypeDefs = QtWidgets.QTextBrowser(self.widget_TypeDefs)
        self.textBrowser_TypeDefs.setObjectName("textBrowser_TypeDefs")
        self.gridLayout.addWidget(self.textBrowser_TypeDefs, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_SearchText = QtWidgets.QLineEdit(self.widget_TypeDefs)
        self.lineEdit_SearchText.setObjectName("lineEdit_SearchText")
        self.horizontalLayout_2.addWidget(self.lineEdit_SearchText)
        self.pushButton_TextUp = QtWidgets.QPushButton(self.widget_TypeDefs)
        self.pushButton_TextUp.setText("")
        self.pushButton_TextUp.setObjectName("pushButton_TextUp")
        self.horizontalLayout_2.addWidget(self.pushButton_TextUp)
        self.pushButton_TextDown = QtWidgets.QPushButton(self.widget_TypeDefs)
        self.pushButton_TextDown.setText("")
        self.pushButton_TextDown.setObjectName("pushButton_TextDown")
        self.horizontalLayout_2.addWidget(self.pushButton_TextDown)
        self.label_FoundCount = QtWidgets.QLabel(self.widget_TypeDefs)
        self.label_FoundCount.setObjectName("label_FoundCount")
        self.horizontalLayout_2.addWidget(self.label_FoundCount)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_TypeDefs)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_TypeDefs)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.widget_TypeDefs)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_ShowTypeDefs = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_ShowTypeDefs.setObjectName("pushButton_ShowTypeDefs")
        self.horizontalLayout.addWidget(self.pushButton_ShowTypeDefs)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.comboBox_SourceFile = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_SourceFile.setObjectName("comboBox_SourceFile")
        self.verticalLayout.addWidget(self.comboBox_SourceFile)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.lineEdit_Search = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_Search.setObjectName("lineEdit_Search")
        self.verticalLayout.addWidget(self.lineEdit_Search)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.tableWidget_ResourceTable = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidget_ResourceTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_ResourceTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_ResourceTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_ResourceTable.setObjectName("tableWidget_ResourceTable")
        self.tableWidget_ResourceTable.setColumnCount(2)
        self.tableWidget_ResourceTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ResourceTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ResourceTable.setHorizontalHeaderItem(1, item)
        self.tableWidget_ResourceTable.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_ResourceTable.verticalHeader().setVisible(False)
        self.tableWidget_ResourceTable.verticalHeader().setDefaultSectionSize(16)
        self.tableWidget_ResourceTable.verticalHeader().setMinimumSectionSize(16)
        self.verticalLayout.addWidget(self.tableWidget_ResourceTable)
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "libPINCE Reference"))
        self.label_FoundCount.setText(_translate("Form", "0/0"))
        self.label_3.setText(_translate("Form", "type_defs(Type Definitions)"))
        self.label_5.setText(_translate("Form", "Search"))
        self.label.setText(_translate("Form", "Source File"))
        self.pushButton_ShowTypeDefs.setText(_translate("Form", "Hide type_defs"))
        self.label_4.setText(_translate("Form", "Search"))
        self.label_2.setText(_translate("Form", "Resources(Mouse-over items to see docstrings)"))
        self.tableWidget_ResourceTable.setSortingEnabled(True)
        item = self.tableWidget_ResourceTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Item Name"))
        item = self.tableWidget_ResourceTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Value"))

