# Form implementation generated from reading ui file 'LogFileWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(582, 558)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_FilePath = QtWidgets.QLabel(parent=Form)
        self.label_FilePath.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_FilePath.setObjectName("label_FilePath")
        self.horizontalLayout.addWidget(self.label_FilePath)
        self.label_LoggingStatus = QtWidgets.QLabel(parent=Form)
        self.label_LoggingStatus.setObjectName("label_LoggingStatus")
        self.horizontalLayout.addWidget(self.label_LoggingStatus)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.textBrowser_LogContent = QtWidgets.QTextBrowser(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.textBrowser_LogContent.setFont(font)
        self.textBrowser_LogContent.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.NoWrap)
        self.textBrowser_LogContent.setObjectName("textBrowser_LogContent")
        self.gridLayout.addWidget(self.textBrowser_LogContent, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_FilePath.setText(_translate("Form", "TextLabel"))
        self.label_LoggingStatus.setText(_translate("Form", "TextLabel"))
