# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'memoryviewerwindow.ui'
#
# Created: Tue Jul  5 14:22:41 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setLineWidth(1)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setOpaqueResize(True)
        self.splitter_3.setHandleWidth(10)
        self.splitter_3.setChildrenCollapsible(True)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(10)
        self.splitter.setObjectName("splitter")
        self.widget_Disassemble = QtWidgets.QWidget(self.splitter)
        self.widget_Disassemble.setObjectName("widget_Disassemble")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_Disassemble)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget_Disassemble = QtWidgets.QTableWidget(self.widget_Disassemble)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.tableWidget_Disassemble.setFont(font)
        self.tableWidget_Disassemble.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_Disassemble.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_Disassemble.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_Disassemble.setObjectName("tableWidget_Disassemble")
        self.tableWidget_Disassemble.setColumnCount(4)
        self.tableWidget_Disassemble.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Disassemble.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Disassemble.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Disassemble.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Disassemble.setHorizontalHeaderItem(3, item)
        self.tableWidget_Disassemble.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_Disassemble.verticalHeader().setDefaultSectionSize(15)
        self.tableWidget_Disassemble.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tableWidget_Disassemble, 0, 0, 1, 1)
        self.widget_Registers = QtWidgets.QWidget(self.splitter)
        self.widget_Registers.setObjectName("widget_Registers")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_Registers)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widget_Registers)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setHandleWidth(10)
        self.splitter_2.setObjectName("splitter_2")
        self.widget_HexView = QtWidgets.QWidget(self.splitter_2)
        self.widget_HexView.setObjectName("widget_HexView")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_HexView)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget_HexView)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.widget_StackView = QtWidgets.QWidget(self.splitter_2)
        self.widget_StackView.setObjectName("widget_StackView")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_StackView)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget_StackView)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.splitter_3)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Memory Viewer"))
        item = self.tableWidget_Disassemble.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Address"))
        item = self.tableWidget_Disassemble.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Bytes"))
        item = self.tableWidget_Disassemble.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Opcodes"))
        item = self.tableWidget_Disassemble.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Comment"))
        self.label_3.setText(_translate("MainWindow", "Reserved for Registers"))
        self.label.setText(_translate("MainWindow", "Reserved for Hexview"))
        self.label_2.setText(_translate("MainWindow", "Reserved for StackView"))

