# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MemoryViewerWindow.ui'
#
# Created: Wed Aug 24 16:42:12 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.splitter_MainMiddle = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_MainMiddle.setLineWidth(1)
        self.splitter_MainMiddle.setOrientation(QtCore.Qt.Vertical)
        self.splitter_MainMiddle.setOpaqueResize(True)
        self.splitter_MainMiddle.setHandleWidth(10)
        self.splitter_MainMiddle.setChildrenCollapsible(True)
        self.splitter_MainMiddle.setObjectName("splitter_MainMiddle")
        self.splitter_Disassemble_Registers = QtWidgets.QSplitter(self.splitter_MainMiddle)
        self.splitter_Disassemble_Registers.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_Disassemble_Registers.setHandleWidth(10)
        self.splitter_Disassemble_Registers.setObjectName("splitter_Disassemble_Registers")
        self.widget_Disassemble = QtWidgets.QWidget(self.splitter_Disassemble_Registers)
        self.widget_Disassemble.setObjectName("widget_Disassemble")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_Disassemble)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget_Disassemble = QtWidgets.QTableWidget(self.widget_Disassemble)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidget_Disassemble.setFont(font)
        self.tableWidget_Disassemble.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_Disassemble.setAutoScroll(False)
        self.tableWidget_Disassemble.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_Disassemble.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_Disassemble.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_Disassemble.setObjectName("tableWidget_Disassemble")
        self.tableWidget_Disassemble.setColumnCount(4)
        self.tableWidget_Disassemble.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Disassemble.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Disassemble.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Disassemble.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Disassemble.setHorizontalHeaderItem(3, item)
        self.tableWidget_Disassemble.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_Disassemble.verticalHeader().setVisible(False)
        self.tableWidget_Disassemble.verticalHeader().setDefaultSectionSize(15)
        self.tableWidget_Disassemble.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tableWidget_Disassemble, 0, 0, 1, 1)
        self.verticalScrollBar_Disassemble = QtWidgets.QScrollBar(self.widget_Disassemble)
        self.verticalScrollBar_Disassemble.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_Disassemble.setObjectName("verticalScrollBar_Disassemble")
        self.gridLayout_2.addWidget(self.verticalScrollBar_Disassemble, 0, 1, 1, 1)
        self.widget_Registers = QtWidgets.QWidget(self.splitter_Disassemble_Registers)
        self.widget_Registers.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_Registers.setObjectName("widget_Registers")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_Registers)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea_Registers = QtWidgets.QScrollArea(self.widget_Registers)
        self.scrollArea_Registers.setWidgetResizable(True)
        self.scrollArea_Registers.setObjectName("scrollArea_Registers")
        self.scrollAreaWidgetContents_Registers = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_Registers.setGeometry(QtCore.QRect(0, 0, 352, 439))
        self.scrollAreaWidgetContents_Registers.setObjectName("scrollAreaWidgetContents_Registers")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_Registers)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_19.addWidget(self.label_3)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents_Registers)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_19.addWidget(self.line)
        self.stackedWidget = QtWidgets.QStackedWidget(self.scrollAreaWidgetContents_Registers)
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 200))
        self.stackedWidget.setObjectName("stackedWidget")
        self.registers_64 = QtWidgets.QWidget()
        self.registers_64.setObjectName("registers_64")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.registers_64)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.RAX = QRegisterLabel(self.registers_64)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.RAX.setFont(font)
        self.RAX.setObjectName("RAX")
        self.verticalLayout_16.addWidget(self.RAX)
        self.RBX = QRegisterLabel(self.registers_64)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.RBX.setFont(font)
        self.RBX.setObjectName("RBX")
        self.verticalLayout_16.addWidget(self.RBX)
        self.RCX = QRegisterLabel(self.registers_64)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.RCX.setFont(font)
        self.RCX.setObjectName("RCX")
        self.verticalLayout_16.addWidget(self.RCX)
        self.RDX = QRegisterLabel(self.registers_64)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.RDX.setFont(font)
        self.RDX.setObjectName("RDX")
        self.verticalLayout_16.addWidget(self.RDX)
        self.RSI = QRegisterLabel(self.registers_64)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.RSI.setFont(font)
        self.RSI.setObjectName("RSI")
        self.verticalLayout_16.addWidget(self.RSI)
        self.RDI = QRegisterLabel(self.registers_64)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.RDI.setFont(font)
        self.RDI.setObjectName("RDI")
        self.verticalLayout_16.addWidget(self.RDI)
        self.RBP = QRegisterLabel(self.registers_64)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.RBP.setFont(font)
        self.RBP.setObjectName("RBP")
        self.verticalLayout_16.addWidget(self.RBP)
        self.RSP = QRegisterLabel(self.registers_64)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.RSP.setFont(font)
        self.RSP.setObjectName("RSP")
        self.verticalLayout_16.addWidget(self.RSP)
        self.horizontalLayout.addLayout(self.verticalLayout_16)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.R8 = QRegisterLabel(self.registers_64)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.R8.setFont(font)
        self.R8.setObjectName("R8")
        self.verticalLayout_3.addWidget(self.R8)
        self.R9 = QRegisterLabel(self.registers_64)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.R9.setFont(font)
        self.R9.setObjectName("R9")
        self.verticalLayout_3.addWidget(self.R9)
        self.R10 = QRegisterLabel(self.registers_64)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.R10.setFont(font)
        self.R10.setObjectName("R10")
        self.verticalLayout_3.addWidget(self.R10)
        self.R11 = QRegisterLabel(self.registers_64)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.R11.setFont(font)
        self.R11.setObjectName("R11")
        self.verticalLayout_3.addWidget(self.R11)
        self.R12 = QRegisterLabel(self.registers_64)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.R12.setFont(font)
        self.R12.setObjectName("R12")
        self.verticalLayout_3.addWidget(self.R12)
        self.R13 = QRegisterLabel(self.registers_64)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.R13.setFont(font)
        self.R13.setObjectName("R13")
        self.verticalLayout_3.addWidget(self.R13)
        self.R14 = QRegisterLabel(self.registers_64)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.R14.setFont(font)
        self.R14.setObjectName("R14")
        self.verticalLayout_3.addWidget(self.R14)
        self.R15 = QRegisterLabel(self.registers_64)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.R15.setFont(font)
        self.R15.setObjectName("R15")
        self.verticalLayout_3.addWidget(self.R15)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_17.addLayout(self.horizontalLayout)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.RIP = QRegisterLabel(self.registers_64)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.RIP.setFont(font)
        self.RIP.setObjectName("RIP")
        self.horizontalLayout_18.addWidget(self.RIP)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem1)
        self.verticalLayout_17.addLayout(self.horizontalLayout_18)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem2)
        self.gridLayout_7.addLayout(self.verticalLayout_17, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.registers_64)
        self.registers_32 = QtWidgets.QWidget()
        self.registers_32.setObjectName("registers_32")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.registers_32)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.EAX = QRegisterLabel(self.registers_32)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.EAX.setFont(font)
        self.EAX.setObjectName("EAX")
        self.verticalLayout_2.addWidget(self.EAX)
        self.EBX = QRegisterLabel(self.registers_32)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.EBX.setFont(font)
        self.EBX.setObjectName("EBX")
        self.verticalLayout_2.addWidget(self.EBX)
        self.ECX = QRegisterLabel(self.registers_32)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ECX.setFont(font)
        self.ECX.setObjectName("ECX")
        self.verticalLayout_2.addWidget(self.ECX)
        self.EDX = QRegisterLabel(self.registers_32)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.EDX.setFont(font)
        self.EDX.setObjectName("EDX")
        self.verticalLayout_2.addWidget(self.EDX)
        self.ESI = QRegisterLabel(self.registers_32)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ESI.setFont(font)
        self.ESI.setObjectName("ESI")
        self.verticalLayout_2.addWidget(self.ESI)
        self.EDI = QRegisterLabel(self.registers_32)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.EDI.setFont(font)
        self.EDI.setObjectName("EDI")
        self.verticalLayout_2.addWidget(self.EDI)
        self.EBP = QRegisterLabel(self.registers_32)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.EBP.setFont(font)
        self.EBP.setObjectName("EBP")
        self.verticalLayout_2.addWidget(self.EBP)
        self.ESP = QRegisterLabel(self.registers_32)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ESP.setFont(font)
        self.ESP.setObjectName("ESP")
        self.verticalLayout_2.addWidget(self.ESP)
        self.EIP = QRegisterLabel(self.registers_32)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.EIP.setFont(font)
        self.EIP.setObjectName("EIP")
        self.verticalLayout_2.addWidget(self.EIP)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_14.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(156, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem4)
        self.gridLayout_6.addLayout(self.verticalLayout_14, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.registers_32)
        self.verticalLayout_19.addWidget(self.stackedWidget)
        self.label_29 = QtWidgets.QLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_19.addWidget(self.label_29)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_Registers)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_19.addWidget(self.line_2)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_5.addWidget(self.label_31)
        self.CF = QFlagRegisterLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.CF.setFont(font)
        self.CF.setObjectName("CF")
        self.verticalLayout_5.addWidget(self.CF)
        self.horizontalLayout_21.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_35 = QtWidgets.QLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_6.addWidget(self.label_35)
        self.PF = QFlagRegisterLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.PF.setFont(font)
        self.PF.setObjectName("PF")
        self.verticalLayout_6.addWidget(self.PF)
        self.horizontalLayout_21.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_37 = QtWidgets.QLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_7.addWidget(self.label_37)
        self.AF = QFlagRegisterLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.AF.setFont(font)
        self.AF.setObjectName("AF")
        self.verticalLayout_7.addWidget(self.AF)
        self.horizontalLayout_21.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_39 = QtWidgets.QLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_8.addWidget(self.label_39)
        self.ZF = QFlagRegisterLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ZF.setFont(font)
        self.ZF.setObjectName("ZF")
        self.verticalLayout_8.addWidget(self.ZF)
        self.horizontalLayout_21.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_41 = QtWidgets.QLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_9.addWidget(self.label_41)
        self.SF = QFlagRegisterLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SF.setFont(font)
        self.SF.setObjectName("SF")
        self.verticalLayout_9.addWidget(self.SF)
        self.horizontalLayout_21.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_43 = QtWidgets.QLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_10.addWidget(self.label_43)
        self.TF = QFlagRegisterLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.TF.setFont(font)
        self.TF.setObjectName("TF")
        self.verticalLayout_10.addWidget(self.TF)
        self.horizontalLayout_21.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_45 = QtWidgets.QLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_11.addWidget(self.label_45)
        self.IF = QFlagRegisterLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.IF.setFont(font)
        self.IF.setObjectName("IF")
        self.verticalLayout_11.addWidget(self.IF)
        self.horizontalLayout_21.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_47 = QtWidgets.QLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_12.addWidget(self.label_47)
        self.DF = QFlagRegisterLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.DF.setFont(font)
        self.DF.setObjectName("DF")
        self.verticalLayout_12.addWidget(self.DF)
        self.horizontalLayout_21.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_49 = QtWidgets.QLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_13.addWidget(self.label_49)
        self.OF = QFlagRegisterLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.OF.setFont(font)
        self.OF.setObjectName("OF")
        self.verticalLayout_13.addWidget(self.OF)
        self.horizontalLayout_21.addLayout(self.verticalLayout_13)
        self.verticalLayout_19.addLayout(self.horizontalLayout_21)
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_19.addWidget(self.label_30)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_Registers)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_19.addWidget(self.line_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.CS = QRegisterLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.CS.setFont(font)
        self.CS.setObjectName("CS")
        self.verticalLayout_4.addWidget(self.CS)
        self.ES = QRegisterLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ES.setFont(font)
        self.ES.setObjectName("ES")
        self.verticalLayout_4.addWidget(self.ES)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.SS = QRegisterLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SS.setFont(font)
        self.SS.setObjectName("SS")
        self.verticalLayout_15.addWidget(self.SS)
        self.GS = QRegisterLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.GS.setFont(font)
        self.GS.setObjectName("GS")
        self.verticalLayout_15.addWidget(self.GS)
        self.horizontalLayout_2.addLayout(self.verticalLayout_15)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.DS = QRegisterLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.DS.setFont(font)
        self.DS.setObjectName("DS")
        self.verticalLayout_18.addWidget(self.DS)
        self.FS = QRegisterLabel(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.FS.setFont(font)
        self.FS.setObjectName("FS")
        self.verticalLayout_18.addWidget(self.FS)
        self.horizontalLayout_2.addLayout(self.verticalLayout_18)
        self.verticalLayout_19.addLayout(self.horizontalLayout_2)
        self.pushButton_ShowFloatRegisters = QtWidgets.QPushButton(self.scrollAreaWidgetContents_Registers)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_ShowFloatRegisters.setFont(font)
        self.pushButton_ShowFloatRegisters.setObjectName("pushButton_ShowFloatRegisters")
        self.verticalLayout_19.addWidget(self.pushButton_ShowFloatRegisters)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem7)
        self.horizontalLayout_4.addLayout(self.verticalLayout_19)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.gridLayout_8.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.scrollArea_Registers.setWidget(self.scrollAreaWidgetContents_Registers)
        self.gridLayout_4.addWidget(self.scrollArea_Registers, 0, 0, 1, 1)
        self.splitter_HexView_StackView = QtWidgets.QSplitter(self.splitter_MainMiddle)
        self.splitter_HexView_StackView.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_HexView_StackView.setHandleWidth(10)
        self.splitter_HexView_StackView.setObjectName("splitter_HexView_StackView")
        self.widget_HexView = QtWidgets.QWidget(self.splitter_HexView_StackView)
        self.widget_HexView.setObjectName("widget_HexView")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_HexView)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea_Hex = QtWidgets.QScrollArea(self.widget_HexView)
        self.scrollArea_Hex.setWidgetResizable(True)
        self.scrollArea_Hex.setObjectName("scrollArea_Hex")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 473, 196))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.listWidget_HexView_Address = QtWidgets.QListWidget(self.scrollAreaWidgetContents_2)
        self.listWidget_HexView_Address.setObjectName("listWidget_HexView_Address")
        self.horizontalLayout_5.addWidget(self.listWidget_HexView_Address)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_5.addWidget(self.line_5)
        self.tableView_HexView_Hex = QHexView(self.scrollAreaWidgetContents_2)
        self.tableView_HexView_Hex.setObjectName("tableView_HexView_Hex")
        self.horizontalLayout_5.addWidget(self.tableView_HexView_Hex)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_5.addWidget(self.line_4)
        self.tableView_HexView_Ascii = QAsciiView(self.scrollAreaWidgetContents_2)
        self.tableView_HexView_Ascii.setObjectName("tableView_HexView_Ascii")
        self.horizontalLayout_5.addWidget(self.tableView_HexView_Ascii)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.gridLayout_11.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.label_HexView_Information = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_HexView_Information.setText("")
        self.label_HexView_Information.setObjectName("label_HexView_Information")
        self.gridLayout_11.addWidget(self.label_HexView_Information, 0, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_11.addWidget(self.line_6, 1, 0, 1, 1)
        self.scrollArea_Hex.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea_Hex, 0, 0, 1, 1)
        self.verticalScrollBar_HexView = QtWidgets.QScrollBar(self.widget_HexView)
        self.verticalScrollBar_HexView.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_HexView.setObjectName("verticalScrollBar_HexView")
        self.gridLayout.addWidget(self.verticalScrollBar_HexView, 0, 1, 1, 1)
        self.widget_StackView = QtWidgets.QWidget(self.splitter_HexView_StackView)
        self.widget_StackView.setObjectName("widget_StackView")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_StackView)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget_StackScreens = QtWidgets.QStackedWidget(self.widget_StackView)
        self.stackedWidget_StackScreens.setObjectName("stackedWidget_StackScreens")
        self.StackTrace = QtWidgets.QWidget()
        self.StackTrace.setObjectName("StackTrace")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.StackTrace)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tableWidget_StackTrace = QtWidgets.QTableWidget(self.StackTrace)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidget_StackTrace.setFont(font)
        self.tableWidget_StackTrace.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_StackTrace.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_StackTrace.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_StackTrace.setObjectName("tableWidget_StackTrace")
        self.tableWidget_StackTrace.setColumnCount(2)
        self.tableWidget_StackTrace.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StackTrace.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StackTrace.setHorizontalHeaderItem(1, item)
        self.tableWidget_StackTrace.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_StackTrace.verticalHeader().setVisible(False)
        self.tableWidget_StackTrace.verticalHeader().setDefaultSectionSize(15)
        self.gridLayout_9.addWidget(self.tableWidget_StackTrace, 0, 0, 1, 1)
        self.stackedWidget_StackScreens.addWidget(self.StackTrace)
        self.Stack = QtWidgets.QWidget()
        self.Stack.setObjectName("Stack")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.Stack)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tableWidget_Stack = QtWidgets.QTableWidget(self.Stack)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidget_Stack.setFont(font)
        self.tableWidget_Stack.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_Stack.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_Stack.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_Stack.setObjectName("tableWidget_Stack")
        self.tableWidget_Stack.setColumnCount(4)
        self.tableWidget_Stack.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Stack.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Stack.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Stack.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Stack.setHorizontalHeaderItem(3, item)
        self.tableWidget_Stack.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_Stack.verticalHeader().setVisible(False)
        self.tableWidget_Stack.verticalHeader().setDefaultSectionSize(15)
        self.gridLayout_10.addWidget(self.tableWidget_Stack, 0, 0, 1, 1)
        self.stackedWidget_StackScreens.addWidget(self.Stack)
        self.gridLayout_3.addWidget(self.stackedWidget_StackScreens, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.splitter_MainMiddle, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuDebug = QtWidgets.QMenu(self.menubar)
        self.menuDebug.setObjectName("menuDebug")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBookmarks = QtWidgets.QAction(MainWindow)
        self.actionBookmarks.setObjectName("actionBookmarks")
        self.actionStackTrace_Info = QtWidgets.QAction(MainWindow)
        self.actionStackTrace_Info.setObjectName("actionStackTrace_Info")
        self.actionInject_so_file = QtWidgets.QAction(MainWindow)
        self.actionInject_so_file.setObjectName("actionInject_so_file")
        self.menuView.addAction(self.actionBookmarks)
        self.menuView.addAction(self.actionStackTrace_Info)
        self.menuTools.addAction(self.actionInject_so_file)
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuDebug.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_StackScreens.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Memory Viewer"))
        item = self.tableWidget_Disassemble.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Address"))
        item = self.tableWidget_Disassemble.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Bytes"))
        item = self.tableWidget_Disassemble.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Opcodes"))
        item = self.tableWidget_Disassemble.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Comment"))
        self.label_3.setText(_translate("MainWindow", "Registers"))
        self.RAX.setText(_translate("MainWindow", "RAX="))
        self.RBX.setText(_translate("MainWindow", "RBX="))
        self.RCX.setText(_translate("MainWindow", "RCX="))
        self.RDX.setText(_translate("MainWindow", "RDX="))
        self.RSI.setText(_translate("MainWindow", "RSI="))
        self.RDI.setText(_translate("MainWindow", "RDI="))
        self.RBP.setText(_translate("MainWindow", "RBP="))
        self.RSP.setText(_translate("MainWindow", "RSP="))
        self.R8.setText(_translate("MainWindow", "R8="))
        self.R9.setText(_translate("MainWindow", "R9="))
        self.R10.setText(_translate("MainWindow", "R10="))
        self.R11.setText(_translate("MainWindow", "R11="))
        self.R12.setText(_translate("MainWindow", "R12="))
        self.R13.setText(_translate("MainWindow", "R13="))
        self.R14.setText(_translate("MainWindow", "R14="))
        self.R15.setText(_translate("MainWindow", "R15="))
        self.RIP.setText(_translate("MainWindow", "RIP="))
        self.EAX.setText(_translate("MainWindow", "EAX="))
        self.EBX.setText(_translate("MainWindow", "EBX="))
        self.ECX.setText(_translate("MainWindow", "ECX="))
        self.EDX.setText(_translate("MainWindow", "EDX="))
        self.ESI.setText(_translate("MainWindow", "ESI="))
        self.EDI.setText(_translate("MainWindow", "EDI="))
        self.EBP.setText(_translate("MainWindow", "EBP="))
        self.ESP.setText(_translate("MainWindow", "ESP="))
        self.EIP.setText(_translate("MainWindow", "EIP="))
        self.label_29.setText(_translate("MainWindow", "Flags"))
        self.label_31.setText(_translate("MainWindow", "CF"))
        self.CF.setText(_translate("MainWindow", "0"))
        self.label_35.setText(_translate("MainWindow", "PF"))
        self.PF.setText(_translate("MainWindow", "0"))
        self.label_37.setText(_translate("MainWindow", "AF"))
        self.AF.setText(_translate("MainWindow", "0"))
        self.label_39.setText(_translate("MainWindow", "ZF"))
        self.ZF.setText(_translate("MainWindow", "0"))
        self.label_41.setText(_translate("MainWindow", "SF"))
        self.SF.setText(_translate("MainWindow", "0"))
        self.label_43.setText(_translate("MainWindow", "TF"))
        self.TF.setText(_translate("MainWindow", "0"))
        self.label_45.setText(_translate("MainWindow", "IF"))
        self.IF.setText(_translate("MainWindow", "0"))
        self.label_47.setText(_translate("MainWindow", "DF"))
        self.DF.setText(_translate("MainWindow", "0"))
        self.label_49.setText(_translate("MainWindow", "OF"))
        self.OF.setText(_translate("MainWindow", "0"))
        self.label_30.setText(_translate("MainWindow", "Segment Registers"))
        self.CS.setText(_translate("MainWindow", "CS="))
        self.ES.setText(_translate("MainWindow", "ES="))
        self.SS.setText(_translate("MainWindow", "SS="))
        self.GS.setText(_translate("MainWindow", "GS="))
        self.DS.setText(_translate("MainWindow", "DS="))
        self.FS.setText(_translate("MainWindow", "FS="))
        self.pushButton_ShowFloatRegisters.setText(_translate("MainWindow", "Show Float Registers"))
        item = self.tableWidget_StackTrace.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Return Address"))
        item = self.tableWidget_StackTrace.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Frame Address"))
        item = self.tableWidget_Stack.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Address"))
        item = self.tableWidget_Stack.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        item = self.tableWidget_Stack.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Int Repr"))
        item = self.tableWidget_Stack.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Float Repr"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuDebug.setTitle(_translate("MainWindow", "Debug"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.actionBookmarks.setText(_translate("MainWindow", "Bookmarks"))
        self.actionStackTrace_Info.setText(_translate("MainWindow", "StackTrace Info"))
        self.actionInject_so_file.setText(_translate("MainWindow", "Inject .so file"))

from GUI.CustomLabels.RegisterLabel import QRegisterLabel
from GUI.CustomTableViews.AsciiView import QAsciiView
from GUI.CustomTableViews.HexView import QHexView
from GUI.CustomLabels.FlagRegisterLabel import QFlagRegisterLabel
