# Form implementation generated from reading ui file 'PointerScannerWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(783, 691)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_ValueType = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox_ValueType.setObjectName("comboBox_ValueType")
        self.horizontalLayout.addWidget(self.comboBox_ValueType)
        spacerItem = QtWidgets.QSpacerItem(684, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 1, 0, 1, 1)
        self.tableWidget_ScanResult = QtWidgets.QTableWidget(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.tableWidget_ScanResult.setFont(font)
        self.tableWidget_ScanResult.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidget_ScanResult.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableWidget_ScanResult.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget_ScanResult.setObjectName("tableWidget_ScanResult")
        self.tableWidget_ScanResult.setColumnCount(0)
        self.tableWidget_ScanResult.setRowCount(0)
        self.tableWidget_ScanResult.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_ScanResult.verticalHeader().setVisible(False)
        self.tableWidget_ScanResult.verticalHeader().setDefaultSectionSize(16)
        self.tableWidget_ScanResult.verticalHeader().setMinimumSectionSize(16)
        self.gridLayout.addWidget(self.tableWidget_ScanResult, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 783, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuRe_scan = QtWidgets.QMenu(parent=self.menubar)
        self.menuRe_scan.setObjectName("menuRe_scan")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(parent=MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(parent=MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionRescan_memory = QtGui.QAction(parent=MainWindow)
        self.actionRescan_memory.setObjectName("actionRescan_memory")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuRe_scan.addAction(self.actionRescan_memory)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRe_scan.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pointer Scanner"))
        self.tableWidget_ScanResult.setSortingEnabled(True)
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuRe_scan.setTitle(_translate("MainWindow", "Pointer Scanner"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionRescan_memory.setText(_translate("MainWindow", "Rescan memory"))
