# Form implementation generated from reading ui file 'Widgets/MonoInvoke/Form/MonoInvokeDialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 320)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_Method = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.label_Method.setFont(font)
        self.label_Method.setText("")
        self.label_Method.setWordWrap(True)
        self.label_Method.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_Method.setObjectName("label_Method")
        self.verticalLayout.addWidget(self.label_Method)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_Result = QtWidgets.QLabel(parent=Dialog)
        self.label_Result.setText("")
        self.label_Result.setWordWrap(True)
        self.label_Result.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_Result.setObjectName("label_Result")
        self.verticalLayout.addWidget(self.label_Result)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_Call = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Call.setObjectName("pushButton_Call")
        self.horizontalLayout.addWidget(self.pushButton_Call)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Invoke"))
        self.pushButton_Call.setText(_translate("Dialog", "Call"))
