# Form implementation generated from reading ui file 'Widgets/MonoFindInstances/Form/MonoFindInstancesDialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_Header = QtWidgets.QLabel(parent=Dialog)
        self.label_Header.setText("")
        self.label_Header.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_Header.setObjectName("label_Header")
        self.verticalLayout.addWidget(self.label_Header)
        self.treeWidget_Instances = QtWidgets.QTreeWidget(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.treeWidget_Instances.setFont(font)
        self.treeWidget_Instances.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.treeWidget_Instances.setWordWrap(False)
        self.treeWidget_Instances.setObjectName("treeWidget_Instances")
        self.verticalLayout.addWidget(self.treeWidget_Instances)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Find Instances"))
        self.treeWidget_Instances.headerItem().setText(0, _translate("Dialog", "Name"))
        self.treeWidget_Instances.headerItem().setText(1, _translate("Dialog", "Value"))
