# Form implementation generated from reading ui file 'Widgets/MonoDissect/Form/MonoDissectDialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 550)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_Search = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_Search.setObjectName("lineEdit_Search")
        self.verticalLayout.addWidget(self.lineEdit_Search)
        self.treeWidget_Mono = QtWidgets.QTreeWidget(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.treeWidget_Mono.setFont(font)
        self.treeWidget_Mono.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.treeWidget_Mono.setWordWrap(False)
        self.treeWidget_Mono.setObjectName("treeWidget_Mono")
        self.verticalLayout.addWidget(self.treeWidget_Mono)
        self.label_Status = QtWidgets.QLabel(parent=Dialog)
        self.label_Status.setText("")
        self.label_Status.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_Status.setObjectName("label_Status")
        self.verticalLayout.addWidget(self.label_Status)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dissect Mono/IL2CPP"))
        self.lineEdit_Search.setPlaceholderText(_translate("Dialog", "Search"))
        self.treeWidget_Mono.headerItem().setText(0, _translate("Dialog", "Name"))
        self.treeWidget_Mono.headerItem().setText(1, _translate("Dialog", "Value"))
