# Form implementation generated from reading ui file 'Widgets/SessionNotes/Form/SessionNotes.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SessionNotes(object):
    def setupUi(self, SessionNotes):
        SessionNotes.setObjectName("SessionNotes")
        SessionNotes.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        SessionNotes.resize(259, 190)
        self.gridLayout = QtWidgets.QGridLayout(SessionNotes)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit_Notes = QtWidgets.QTextEdit(parent=SessionNotes)
        self.textEdit_Notes.setMinimumSize(QtCore.QSize(50, 50))
        self.textEdit_Notes.setObjectName("textEdit_Notes")
        self.gridLayout.addWidget(self.textEdit_Notes, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=SessionNotes)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(SessionNotes)
        QtCore.QMetaObject.connectSlotsByName(SessionNotes)

    def retranslateUi(self, SessionNotes):
        _translate = QtCore.QCoreApplication.translate
        SessionNotes.setWindowTitle(_translate("SessionNotes", "Notes"))
        self.label.setText(_translate("SessionNotes", "Session Notes"))
