# Form implementation generated from reading ui file 'Widgets/Structures/Form/MemberEditorDialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(340, 406)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_Name = QtWidgets.QLabel(parent=Dialog)
        self.label_Name.setObjectName("label_Name")
        self.gridLayout.addWidget(self.label_Name, 0, 0, 1, 1)
        self.lineEdit_Name = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_Name.setObjectName("lineEdit_Name")
        self.gridLayout.addWidget(self.lineEdit_Name, 0, 1, 1, 1)
        self.label_Offset = QtWidgets.QLabel(parent=Dialog)
        self.label_Offset.setObjectName("label_Offset")
        self.gridLayout.addWidget(self.label_Offset, 1, 0, 1, 1)
        self.lineEdit_Offset = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_Offset.setObjectName("lineEdit_Offset")
        self.gridLayout.addWidget(self.lineEdit_Offset, 1, 1, 1, 1)
        self.label_Kind = QtWidgets.QLabel(parent=Dialog)
        self.label_Kind.setObjectName("label_Kind")
        self.gridLayout.addWidget(self.label_Kind, 2, 0, 1, 1)
        self.comboBox_Kind = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_Kind.setObjectName("comboBox_Kind")
        self.gridLayout.addWidget(self.comboBox_Kind, 2, 1, 1, 1)
        self.label_Type = QtWidgets.QLabel(parent=Dialog)
        self.label_Type.setObjectName("label_Type")
        self.gridLayout.addWidget(self.label_Type, 3, 0, 1, 1)
        self.comboBox_Type = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_Type.setObjectName("comboBox_Type")
        self.gridLayout.addWidget(self.comboBox_Type, 3, 1, 1, 1)
        self.label_Length = QtWidgets.QLabel(parent=Dialog)
        self.label_Length.setObjectName("label_Length")
        self.gridLayout.addWidget(self.label_Length, 4, 0, 1, 1)
        self.lineEdit_Length = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_Length.setObjectName("lineEdit_Length")
        self.gridLayout.addWidget(self.lineEdit_Length, 4, 1, 1, 1)
        self.label_Repr = QtWidgets.QLabel(parent=Dialog)
        self.label_Repr.setObjectName("label_Repr")
        self.gridLayout.addWidget(self.label_Repr, 5, 0, 1, 1)
        self.comboBox_Repr = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_Repr.setObjectName("comboBox_Repr")
        self.gridLayout.addWidget(self.comboBox_Repr, 5, 1, 1, 1)
        self.label_Endian = QtWidgets.QLabel(parent=Dialog)
        self.label_Endian.setObjectName("label_Endian")
        self.gridLayout.addWidget(self.label_Endian, 6, 0, 1, 1)
        self.comboBox_Endian = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_Endian.setObjectName("comboBox_Endian")
        self.gridLayout.addWidget(self.comboBox_Endian, 6, 1, 1, 1)
        self.label_StructRef = QtWidgets.QLabel(parent=Dialog)
        self.label_StructRef.setObjectName("label_StructRef")
        self.gridLayout.addWidget(self.label_StructRef, 7, 0, 1, 1)
        self.comboBox_StructRef = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_StructRef.setObjectName("comboBox_StructRef")
        self.gridLayout.addWidget(self.comboBox_StructRef, 7, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 8, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Member"))
        self.label_Name.setText(_translate("Dialog", "Name"))
        self.label_Offset.setText(_translate("Dialog", "Offset (hex)"))
        self.label_Kind.setText(_translate("Dialog", "Kind"))
        self.label_Type.setText(_translate("Dialog", "Value type"))
        self.label_Length.setText(_translate("Dialog", "Length"))
        self.label_Repr.setText(_translate("Dialog", "Repr"))
        self.label_Endian.setText(_translate("Dialog", "Endianness"))
        self.label_StructRef.setText(_translate("Dialog", "Structure"))
