# Form implementation generated from reading ui file 'Widgets/Structures/Form/StructureViewDialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(560, 460)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_Base = QtWidgets.QLabel(parent=Dialog)
        self.label_Base.setObjectName("label_Base")
        self.gridLayout.addWidget(self.label_Base, 0, 0, 1, 1)
        self.lineEdit_Base = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_Base.setObjectName("lineEdit_Base")
        self.gridLayout.addWidget(self.lineEdit_Base, 0, 1, 1, 1)
        self.treeWidget_View = QtWidgets.QTreeWidget(parent=Dialog)
        self.treeWidget_View.setObjectName("treeWidget_View")
        self.gridLayout.addWidget(self.treeWidget_View, 1, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Structure view"))
        self.label_Base.setText(_translate("Dialog", "Base address"))
        self.treeWidget_View.headerItem().setText(0, _translate("Dialog", "Offset"))
        self.treeWidget_View.headerItem().setText(1, _translate("Dialog", "Name"))
        self.treeWidget_View.headerItem().setText(2, _translate("Dialog", "Type"))
        self.treeWidget_View.headerItem().setText(3, _translate("Dialog", "Value"))
