# Form implementation generated from reading ui file 'Widgets/Structures/Form/StructureEditorDialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(460, 460)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_Name = QtWidgets.QLabel(parent=Dialog)
        self.label_Name.setObjectName("label_Name")
        self.gridLayout.addWidget(self.label_Name, 0, 0, 1, 1)
        self.lineEdit_Name = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_Name.setObjectName("lineEdit_Name")
        self.gridLayout.addWidget(self.lineEdit_Name, 0, 1, 1, 1)
        self.treeWidget_Members = QtWidgets.QTreeWidget(parent=Dialog)
        self.treeWidget_Members.setRootIsDecorated(False)
        self.treeWidget_Members.setObjectName("treeWidget_Members")
        self.gridLayout.addWidget(self.treeWidget_Members, 1, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Add = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Add.setObjectName("pushButton_Add")
        self.horizontalLayout.addWidget(self.pushButton_Add)
        self.pushButton_Edit = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Edit.setObjectName("pushButton_Edit")
        self.horizontalLayout.addWidget(self.pushButton_Edit)
        self.pushButton_Remove = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Remove.setObjectName("pushButton_Remove")
        self.horizontalLayout.addWidget(self.pushButton_Remove)
        self.pushButton_Up = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Up.setObjectName("pushButton_Up")
        self.horizontalLayout.addWidget(self.pushButton_Up)
        self.pushButton_Down = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Down.setObjectName("pushButton_Down")
        self.horizontalLayout.addWidget(self.pushButton_Down)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Edit structure"))
        self.label_Name.setText(_translate("Dialog", "Name"))
        self.treeWidget_Members.headerItem().setText(0, _translate("Dialog", "Offset"))
        self.treeWidget_Members.headerItem().setText(1, _translate("Dialog", "Name"))
        self.treeWidget_Members.headerItem().setText(2, _translate("Dialog", "Type"))
        self.pushButton_Add.setText(_translate("Dialog", "Add"))
        self.pushButton_Edit.setText(_translate("Dialog", "Edit"))
        self.pushButton_Remove.setText(_translate("Dialog", "Remove"))
        self.pushButton_Up.setText(_translate("Dialog", "Up"))
        self.pushButton_Down.setText(_translate("Dialog", "Down"))
