# Form implementation generated from reading ui file 'Widgets/Structures/Form/StructuresWindow.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 450)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.treeWidget_Structures = QtWidgets.QTreeWidget(parent=Form)
        self.treeWidget_Structures.setRootIsDecorated(False)
        self.treeWidget_Structures.setObjectName("treeWidget_Structures")
        self.gridLayout.addWidget(self.treeWidget_Structures, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_New = QtWidgets.QPushButton(parent=Form)
        self.pushButton_New.setObjectName("pushButton_New")
        self.horizontalLayout.addWidget(self.pushButton_New)
        self.pushButton_Edit = QtWidgets.QPushButton(parent=Form)
        self.pushButton_Edit.setObjectName("pushButton_Edit")
        self.horizontalLayout.addWidget(self.pushButton_Edit)
        self.pushButton_Delete = QtWidgets.QPushButton(parent=Form)
        self.pushButton_Delete.setObjectName("pushButton_Delete")
        self.horizontalLayout.addWidget(self.pushButton_Delete)
        self.pushButton_ViewAtAddress = QtWidgets.QPushButton(parent=Form)
        self.pushButton_ViewAtAddress.setObjectName("pushButton_ViewAtAddress")
        self.horizontalLayout.addWidget(self.pushButton_ViewAtAddress)
        self.pushButton_AddToTable = QtWidgets.QPushButton(parent=Form)
        self.pushButton_AddToTable.setObjectName("pushButton_AddToTable")
        self.horizontalLayout.addWidget(self.pushButton_AddToTable)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Structures"))
        self.treeWidget_Structures.headerItem().setText(0, _translate("Form", "Name"))
        self.pushButton_New.setText(_translate("Form", "New"))
        self.pushButton_Edit.setText(_translate("Form", "Edit"))
        self.pushButton_Delete.setText(_translate("Form", "Delete"))
        self.pushButton_ViewAtAddress.setText(_translate("Form", "View at address…"))
        self.pushButton_AddToTable.setText(_translate("Form", "Add to address table"))
