name: Release AppImage

on:
  push:
    tags:
      - "v*.*"
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt install -y fuse3
      - name: Build
        run: ./ci/package.sh
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          files: |
            ci/PINCE-x86_64.AppImage
            ci/PINCE-x86_64.AppImage.zsync
